#!/bin/bash

#=========================System Information Section=================================
# Get the current username
USERNAME=$(whoami)
# Get the current date and time
DATE_TIME=$(date +"%Y-%m-%d/%H:%M:%S")
# Get the current hostname
HOSTNAME=$(hostname)
#DISTROWITHVERSION=$(lsb_release -a 2>/dev/null | grep Description |sed 's/.*Ubuntu/Ubuntu/')
# Get Distribution and Version
DISTROWITHVERSION=$(< /etc/os-release grep PRETTY_NAME|sed 's/.*"\(.*\)".*/\1/')
# Get Uptime
UPTIME=$(uptime|awk '{print $1}')


# Display the system report
echo "System Report generated by $USERNAME, $DATE_TIME"
echo 
echo "System Information"
echo "------------------"
echo "Hostname: $HOSTNAME"
echo "OS: $DISTROWITHVERSION"
echo "Uptime: $UPTIME"

